on: [push]

jobs:
  notifications:
    runs-on: ubuntu-latest
    name: Notification Test
    steps:
    - name: notifications action step
      uses: TelltaleGames/notify-action@main
      with:
        notifications: ${{ secrets.BUILD_NOTIFICATIONS_DATA }}
      env:
        BUILD_STATUS: "Build ${{ job.status }}: ${{ github.repository }} (${{ github.run_number }})"
